name: Compile LwM2M type definitions

on:
  push:
    branches:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm ci

      - name: Clone LwM2M object registry
        run:
          git clone https://github.com/OpenMobileAlliance/lwm2m-registry.git
          --depth 1

      - name: Run unit tests
        run: npm test

      - name: Create LwM2M types
        run: npx tsx cli/generate-types.ts

      - name: Create the JSON Schema
        run: npx tsx cli/generate-json-schema.ts

      - name: Format result
        run: npx prettier --write ./

      - name: Make sure result compiles
        run: npx tsc

      - name: Compile JS exports
        run: npx swc -d types-dist ./types

      - name: Make sure example runs
        run: npx tsx ./example.ts
